"""add items.created_by

Revision ID: d7864db5cc88
Revises: 0dc75f0ce83d
Create Date: 2026-07-11 01:49:40.724102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7864db5cc88"
down_revision: Union[str, Sequence[str], None] = "0dc75f0ce83d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "items", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "items", type_="foreignkey")
    op.drop_column("items", "created_by")
    # ### end Alembic commands ###
